MAINTAINERCLEANFILES   = Makefile.in

SUBDIRS                =

if TTS_WEBSOCKET_PLUGIN
SUBDIRS               += tts-websocket
endif

if DEMORECOG_PLUGIN
SUBDIRS               += demo-recog
endif

if DEMOVERIFIER_PLUGIN
SUBDIRS               += demo-verifier
endif

if RECORDER_PLUGIN
SUBDIRS               += mrcp-recorder
endif
